AWSTemplateFormatVersion: 2010-09-09
Resources:
  Vpc:
    Type: "AWS::EC2::VPC"
    Properties:
      CidrBlock: 10.0.0.0/16 #required
      Tags:
        - Key: Name
          Value: spn-vpc-for-kafka
  VpcSubnet1:
    Type: "AWS::EC2::Subnet"
    Properties:
      AvailabilityZone: ap-southeast-1a
      CidrBlock: 10.0.1.0/24 #required
      Tags:
        - Key: Name
          Value: spn-vpc-kafka-subnet1
      VpcId: !Ref Vpc #required
  VpcSubnet2:
    Type: "AWS::EC2::Subnet"
    Properties:
      AvailabilityZone: ap-southeast-1b
      CidrBlock: 10.0.2.0/24 #required
      Tags:
        - Key: Name
          Value: spn-vpc-kafka-subnet2
      VpcId: !Ref Vpc #required
  VpcSubnet3:
    Type: "AWS::EC2::Subnet"
    Properties:
      AvailabilityZone: ap-southeast-1c
      CidrBlock: 10.0.3.0/24 #required
      Tags:
        - Key: Name
          Value: spn-vpc-kafka-subnet3
      VpcId: !Ref Vpc #required
  
  KafkaCluster:
    Type: 'AWS::MSK::Cluster'
    Properties:
      ClusterName: spn-kafka-cluster
      NumberOfBrokerNodes: 3
      KafkaVersion: "2.2.1"
      BrokerNodeGroupInfo:
        BrokerAZDistribution: DEFAULT
        ClientSubnets: 
          - !Ref VpcSubnet1
          - !Ref VpcSubnet2
          - !Ref VpcSubnet3
        InstanceType: "kafka.m5.large"
    Metadata:
      'AWS::CloudFormation::Designer':
        id: d42ad464-1955-42c1-89d5-0522cd4775a7
Metadata:
  'AWS::CloudFormation::Designer':
    d42ad464-1955-42c1-89d5-0522cd4775a7:
      size:
        width: 60
        height: 60
      position:
        x: -110
        'y': 66.58333333333333
      z: 0
