AWSTemplateFormatVersion: 2010-09-09
Resources:
  VPC:
    Type: "AWS::EC2::VPC"
    Properties:
      CidrBlock: 10.0.0.0/16 #required
      Tags:
        - Key: Name
          Value: "souphorn-vpc"
  IntegetGateway:
    Type: "AWS::EC2::InternetGateway"
    Properties:
      Tags:
        - Key: Name
          Value: "souphorn-gateway"
  VPCInternetGatewayAttachment:
    Type: "AWS::EC2::VPCGatewayAttachment"
    Properties:
      InternetGatewayId: !Ref IntegetGateway
      VpcId: !Ref VPC #required
  